name:  'Promote Release Candidate Scan'

#$(TeamProject)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

variables:
- name: applicationName
  value: verademo-azure
- name: vid
  value: testid
- name: vkey
  value: testkey
- name: wrapper_version
  value: 23.1.10.5
steps:
  
  - script: |
      echo ${{ variables.wrapper_version }} # outputs initialValue
      echo $(wrapper_version)
    displayName: First variable pass

 # - bash: echo "##vso[task.setvariable variable=one]secondValue"
 #   displayName: Set new variable value

 # - script: |
 #     echo ${{ variables.one }} # outputs initialValue
 #     echo $(one) # outputs secondValue
 #   displayName: Second variable pass

  - script: | 
      curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$version/vosp-api-wrappers-java-$(wrapper_version)-dist.zip -o dist.zip
    displayName: Downloading the latest version of the Veracode Java API
    
  - script: ls -la
    displayName: Show Contents
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.zip'
      destinationFolder: '.'
      cleanDestinationFolder: true
      overwriteExistingFiles: false

  #- script: |
  #     java -jar VeracodeJavaAPI.jar -vid $(vid) -vkey $(vkey) -action getapplist | tee appidlist.txt
  #  displayName: Pulling the Sandbox ID List