# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none
   # - main
pr: none

resources:
  repositories:
    - repository: devops-scripts
      type: github
      name: veracode-dmedeiros/devops-scripts-azure-devops
      endpoint: Github Repo Access #Connection name of GitHub App. Can be name of a Service Connection to GitHub as well.

pool:
  #vmImage: ubuntu-latest
  vmImage: 'windows-latest'

variables:
- group: 'Veracode Credentials' # Reference the library containing Veracode Credentials
- group: 'SCA Agent Configuration'

stages: 
- stage: Build
        
  jobs:
  - job: Build_Debug
    displayName: Debug Build

    steps:
    - template: steps/abstract-build-steps.yml@devops-scripts
      parameters:
        buildConfiguration: 'Debug'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.StagingDirectory)
        artifactName: WebApp_Debug

- stage: Security_Testing
  jobs:       
    
  - template: jobs/veracode-sca-agent-job.yml@devops-scripts
  
  - job: SAST_Security_Testing
    displayName: Static Analysis Security Testing

    
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      displayName: "Download Artifact"
      inputs:
        targetPath: $(Build.StagingDirectory)
        artifact: WebApp_Debug 
        
    - script: ls -la $(Agent.BuildDirectory)
    - script: ls -la $(Build.StagingDirectory)
      displayName: "Show Workspace Contents"
   
    - script: echo 'Prepare Veracode Pipeline SAST'
    - script: curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      displayName: "Download Pipeline Scan"

    - script: unzip -o pipeline-scan-LATEST.zip
      displayName: "Unzip Pipeline Scan"

    - script: java -jar pipeline-scan.jar --version
      displayName: "Pipeline Scan Version" 
      
    - script: java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f $(Build.StagingDirectory)\$(system.teamProject).zip || true
      displayName: "Running Analysis"
      
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml   
      displayName: 'Run a multi-line script'
      

