name:  'Promote Release Candidate Scan'

#$(TeamProject)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

parameters:
  - name: vid
    displayName: veracode-api-id
    default: ""
    type: string
  - name: vkey
    displayName: veracode-api-key
    default: ""
    type: string
  - name: appName
    default: "verademo-react-azure-devops"
    type: string
  - name: sandboxName
    default: "Release Candidate"
    type: string

steps:
  - script: java --version
    continueOnError: true
    displayName: Report Java Version installed

  - pwsh: |
      $versionstring = curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | Out-String -Stream | Select-String -Pattern 'latest';
      $wrapper_version = $versionstring -replace '\s','' -replace '<latest>','' -replace '</latest>','';
      echo $wrapper_version
      curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION-dist.zip -o $(Build.ArtifactStagingDirectory)/dist.zip
      7z e $(Build.ArtifactStagingDirectory)/dist.zip -o$(Build.ArtifactStagingDirectory)/extract/ -y
    displayName: Downloading the latest version of the Veracode Java API
    enabled: true
 
  - script: ls -la $(Build.ArtifactStagingDirectory)
    displayName: Show Artifact Directory Content

  - script: |
      ls -la $(Build.ArtifactStagingDirectory)/extract/
    displayName: Show Extract Directory Content
    enabled: true
    
  - script: |
      java -jar $(Build.ArtifactStagingDirectory)/extract/VeracodeJavaAPI.jar -version
    displayName: Veracode Wrapper Version
    enabled: false
    
  - script: |
      echo $(vid);
      echo $(vkey);
    
  - script: |
      java -jar $(Build.ArtifactStagingDirectory)/extract/VeracodeJavaAPI.jar -vid $(vid) -vkey $(vkey) -action getapplist 
        #| tee appidlist.txt
    displayName: Pulling the Application List
    enabled: true
 
  - script: |
      java -jar $(Build.ArtifactStagingDirectory)/extract/VeracodeJavaAPI.jar -vid $(vid) -vkey $(vkey) -action getapplist | tee appidlist.txt
      $veracodeappid = (Get-Content .\appidlist.txt | Select-String $(appName)).Line.Split('"')[1]
      echo $veracodeappid
    displayName: Pulling the Sandbox ID List
    enabled: false
  

  #- script: |
  #    java -jar $(Build.ArtifactStagingDirectory)/extract/VeracodeJavaAPI.jar -vid $(vid) -vkey $(vkey) -action getsandboxlist -appid $veracodeappid | tee sandboxlist.txt
  #        $veracodesandboxid = (Get-Content .\sandboxlist.txt | Select-String -Pattern "sandbox_id=").Line.Split('"')[9] | Select-Object -Last 1
  #        Write-Output "Pulling the Build ID List"